Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2019-03, with the labels that each got.

#2 Initial Declarative, Addon Patterns
  .gitignore
  Gopkg.lock
  Gopkg.toml
  docs/addon/walkthrough/README.md
  docs/addon/walkthrough/tests.md
  examples/dashboard-operator/.gitignore
  examples/dashboard-operator/Dockerfile
  examples/dashboard-operator/Makefile
  examples/dashboard-operator/PROJECT
  examples/dashboard-operator/channels/packages/dashboard/1.8.3/manifest.yaml
  examples/dashboard-operator/channels/stable
  examples/dashboard-operator/cmd/manager/main.go
  examples/dashboard-operator/config/crds/addons_v1alpha1_dashboard.yaml
  examples/dashboard-operator/config/default/kustomization.yaml
  examples/dashboard-operator/config/default/manager_image_patch.yaml
  examples/dashboard-operator/config/manager/manager.yaml
  examples/dashboard-operator/config/rbac/rbac_role.yaml
  examples/dashboard-operator/config/rbac/rbac_role_binding.yaml
  examples/dashboard-operator/config/samples/addons_v1alpha1_dashboard.yaml
  examples/dashboard-operator/hack/boilerplate.go.txt
  examples/dashboard-operator/pkg/apis/addons/group.go
  examples/dashboard-operator/pkg/apis/addons/v1alpha1/dashboard_types.go
  examples/dashboard-operator/pkg/apis/addons/v1alpha1/dashboard_types_test.go
  examples/dashboard-operator/pkg/apis/addons/v1alpha1/doc.go
  examples/dashboard-operator/pkg/apis/addons/v1alpha1/register.go
  examples/dashboard-operator/pkg/apis/addons/v1alpha1/v1alpha1_suite_test.go
  examples/dashboard-operator/pkg/apis/addons/v1alpha1/zz_generated.deepcopy.go
  examples/dashboard-operator/pkg/apis/addtoscheme_addons_v1alpha1.go
  examples/dashboard-operator/pkg/apis/apis.go
  examples/dashboard-operator/pkg/controller/add_dashboard.go
  examples/dashboard-operator/pkg/controller/controller.go
  examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller.go
  examples/dashboard-operator/pkg/webhook/webhook.go
  pkg/patterns/addon/init.go
  pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
  pkg/patterns/addon/pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/patterns/addon/pkg/loaders/fs.go
  pkg/patterns/addon/pkg/loaders/types.go
  pkg/patterns/addon/pkg/status/aggregate.go
  pkg/patterns/addon/pkg/status/basic.go
  pkg/patterns/declarative/labels.go
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/ownerref.go
  pkg/patterns/declarative/pkg/kubectlcmd/client.go
  pkg/patterns/declarative/pkg/kubectlcmd/client_test.go
  pkg/patterns/declarative/pkg/manifest/objects.go
  pkg/patterns/declarative/pkg/watch/dynamic.go
  pkg/patterns/declarative/reconciler.go
  pkg/patterns/declarative/sort.go
  pkg/patterns/declarative/status.go
  pkg/patterns/declarative/watch.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XXL

#8 README: add a temporary warning sign
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#10 add empty test targets
  hack/ci/test.sh
  pkg/doc.go
  pkg/patterns/addon/pkg/doc.go
  pkg/patterns/doc.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#11 Fix merge conflict section in walkthrough
  docs/addon/walkthrough/README.md
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#13 Add johnsonj to owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/XS

#14 declarative: Add WithApplyPrune
  examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller.go
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/M

#22 pkg/patterns/addon/init: Drop flag parsing
  pkg/patterns/addon/init.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#18 Implement Application management
  examples/dashboard-operator/channels/packages/dashboard/1.8.3/manifest.yaml
  examples/dashboard-operator/config/crds/app_v1beta1_application.yaml
  examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller.go
  pkg/patterns/addon/application.go
  pkg/patterns/addon/pkg/status/aggregate.go
  pkg/patterns/declarative/application.go
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/pkg/kubectlcmd/client.go
  pkg/patterns/declarative/pkg/manifest/objects.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#23 docs/addon/walkthrough: Cleanup pass
  doc.go
  docs/addon/walkthrough/README.md
  examples/dashboard-operator/config/default/kustomization.yaml
  examples/dashboard-operator/config/default/manager_resource_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#24 Add license notice to each files
  examples/dashboard-operator/Dockerfile
  examples/dashboard-operator/Makefile
  examples/dashboard-operator/pkg/apis/addons/v1alpha1/zz_generated.deepcopy.go
  hack/ci/e2e.sh
  hack/ci/test.sh
  pkg/doc.go
  pkg/patterns/addon/application.go
  pkg/patterns/addon/init.go
  pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
  pkg/patterns/addon/pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/patterns/addon/pkg/doc.go
  pkg/patterns/addon/pkg/loaders/fs.go
  pkg/patterns/addon/pkg/loaders/types.go
  pkg/patterns/addon/pkg/status/aggregate.go
  pkg/patterns/addon/pkg/status/basic.go
  pkg/patterns/declarative/application.go
  pkg/patterns/declarative/labels.go
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/ownerref.go
  pkg/patterns/declarative/pkg/kubectlcmd/client_test.go
  pkg/patterns/declarative/pkg/manifest/objects.go
  pkg/patterns/declarative/pkg/watch/dynamic.go
  pkg/patterns/declarative/reconciler.go
  pkg/patterns/declarative/sort.go
  pkg/patterns/declarative/status.go
  pkg/patterns/declarative/watch.go
  pkg/patterns/doc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/L

#26 examples/dashboard-operator: fake vendor directory
  examples/dashboard-operator/Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#27 dashboard-operator: default image name to $USER/dashboard-operator
  examples/dashboard-operator/Makefile
  examples/dashboard-operator/config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#19 Implement golden file based tests
  Gopkg.lock
  examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller.go
  examples/dashboard-operator/pkg/controller/dashboard/dashboard_controller_test.go
  examples/dashboard-operator/pkg/controller/dashboard/tests/simple.in.yaml
  examples/dashboard-operator/pkg/controller/dashboard/tests/simple.out.yaml
  hack/ci/test.sh
  pkg/patterns/declarative/application.go
  pkg/test/doc.go
  pkg/test/golden/doc.go
  pkg/test/golden/validator.go
  pkg/test/mocks/cache.go
  pkg/test/mocks/client.go
  pkg/test/mocks/manager.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XL

#28 Expose NewObject function in manifest package externally
  pkg/patterns/declarative/pkg/manifest/objects.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#31 Fix (accidentally?) duplicated copyright block in fs.go
  pkg/patterns/addon/pkg/loaders/fs.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#30 Add emacs temp files to .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#29 Make the default manifest loader pluggable
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#32 declarative,addon: Configure the filesystem loader in addon.Init
  pkg/patterns/addon/init.go
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S
