Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2020-01, with the labels that each got.

#67 Update to controller-runtime 0.4.0
  examples/dashboard-operator/go.mod
  examples/dashboard-operator/go.sum
  go.mod
  go.sum
  pkg/test/mocks/manager.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XXL

#69 Change imports in examples directory to use fully qualified path
  examples/dashboard-operator/controllers/dashboard_controller.go
  examples/dashboard-operator/controllers/dashboard_controller_test.go
  examples/dashboard-operator/go.mod
  examples/dashboard-operator/main.go
  hack/ci/test.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/S

#71 Add field names when create types.NamespacedName
  pkg/patterns/addon/pkg/status/aggregate.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#60 Fetch manifests over http/https
  go.mod
  pkg/patterns/addon/init.go
  pkg/patterns/addon/pkg/loaders/fs.go
  pkg/patterns/addon/pkg/loaders/http.go
  pkg/patterns/addon/pkg/loaders/types.go
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#61 Replace yaml.v2 with sigs.k8s.io/yaml
  go.mod
  pkg/patterns/addon/pkg/loaders/types.go
Labels: approved, cncf-cla: yes, sig/api-machinery, size/XS

#72 Fix command for generate patch yaml file
  docs/addon/walkthrough/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/S

#62 Support multiple packages in a channel manifest file
  docs/addon/walkthrough/README.md
  examples/dashboard-operator/channels/stable
  go.mod
  go.sum
  pkg/patterns/addon/pkg/loaders/fs.go
  pkg/patterns/addon/pkg/loaders/types.go
  pkg/patterns/addon/pkg/loaders/versions_test.go
  pkg/test/mocks/client.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L
