Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2020-11, with the labels that each got.

#127 deps: bump to controller-runtime v0.7.0-alpha.5
  go.mod
  go.sum
  pkg/patterns/declarative/metrics.go
  pkg/patterns/declarative/metrics_test.go
  pkg/patterns/declarative/pkg/watch/dynamic.go
  pkg/patterns/declarative/reconciler.go
  pkg/test/mocks/cache.go
  pkg/test/mocks/client.go
  pkg/test/mocks/manager.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#124 Remove duplicate fn
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#123 Fix metrics reconcilation
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#125 Use latest version for tests
  examples/guestbook-operator/controllers/guestbook_controller.go
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/L

#126 Cleanup naming in utils for better clarity
  utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#134 github actions tests: replace set-env with GITHUB_ENV
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#133 Various docs fixes
  README.md
  docs/addon/walkthrough/README.md
  docs/addon/walkthrough/tests.md
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S
