Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2020-07, with the labels that each got.

#101 Uses new apply function so we don't need kubectl
  go.mod
  go.sum
  pkg/patterns/declarative/pkg/applier/direct.go
  pkg/patterns/declarative/pkg/applier/exec.go
  pkg/patterns/declarative/pkg/applier/exec_test.go
  pkg/patterns/declarative/pkg/applier/type.go
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/L

#106 github actions: check goimports/gofmt
  .github/workflows/main.yml
  go.mod
  go.sum
  tools.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/M

#109 Modify CI Test to Fetch kubebuilder Release Binary
  hack/ci/fetch_kubebuilder_release_bin.sh
  hack/ci/test.sh
  hack/smoketest.go
  pkg/patterns/addon/pkg/loaders/http.go
  pkg/patterns/declarative/pkg/applier/direct.go
  pkg/patterns/declarative/pkg/applier/exec.go
  pkg/patterns/declarative/pkg/manifest/objects_test.go
  pkg/test/mocks/cache.go
  pkg/test/mocks/manager.go
  utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/L

#103 Adds function for parsing list
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/M

#98 Add Reconciliation Metrics Functionality
  docs/addon/walkthrough/README.md
  go.mod
  go.sum
  pkg/patterns/declarative/metrics.go
  pkg/patterns/declarative/metrics_test.go
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/reconciler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/api-machinery, size/XXL

#115 Kind e2e test using github actions
  .github/workflows/kind-config.yaml
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#114 .gitignore: don't ignore vendor
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#108 Fix goimports and go mod tidy
  go.mod
  go.sum
  utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S

#107 github actions: try running go mod tidy also
  .github/workflows/main.yml
  go.mod
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/S
