Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2021-09, with the labels that each got.

#175 Update go1.16 in github workflow
  .github/workflows/main.yml
Labels: sig/api-machinery, size/XS, lgtm, cncf-cla: yes, approved

#173 Fix namespace setting with direct applier
  pkg/patterns/declarative/pkg/applier/direct.go
  pkg/patterns/declarative/pkg/applier/exec.go
  pkg/patterns/declarative/pkg/applier/exec_test.go
  pkg/patterns/declarative/pkg/applier/type.go
  pkg/patterns/declarative/reconciler.go
Labels: sig/api-machinery, lgtm, cncf-cla: yes, approved, size/L

#177 Make atoato88 an approver
  OWNERS
Labels: sig/api-machinery, size/XS, lgtm, cncf-cla: yes, approved

#178 Fix missing kubebuilder flag in walkthrough
  docs/addon/walkthrough/README.md
Labels: sig/api-machinery, ok-to-test, size/XS, lgtm, cncf-cla: yes, approved

#169 bump k8s to 1.22
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
  go.mod
  go.sum
Labels: sig/api-machinery, lgtm, cncf-cla: yes, approved, size/L

#179 Update walkthrough docs to fit latest code
  docs/addon/walkthrough/README.md
Labels: sig/api-machinery, size/XS, lgtm, cncf-cla: yes, approved
