Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2021-03, with the labels that each got.

#155 Update go.mod for go 1.16
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XL

#149 Fix to get the correct dns domain
  utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS

#144 Add template for issue and PR
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/M

#148 Add unit tests for objects.go
  go.mod
  go.sum
  pkg/patterns/declarative/pkg/manifest/objects_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XL

#153 Change Secrets with Secret in sort.go
  pkg/patterns/declarative/sort.go
Labels: approved, cncf-cla: yes, lgtm, sig/api-machinery, size/XS
