Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2023-09, with the labels that each got.

#349 Bump controller-runtime to v0.15.2
  go.mod
  go.sum
Labels: size/XS, lgtm, cncf-cla: yes, approved

#352 :warning: Bump controller-runtime to 0.16.1
  .github/workflows/main.yml
  applylib/go.mod
  applylib/go.sum
  dev/format-gomod
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
  examples/guestbook-operator/main.go
  go.mod
  go.sum
  pkg/patterns/declarative/metrics_test.go
  pkg/patterns/declarative/pkg/applier/direct.go
  pkg/test/testreconciler/simpletest/controller_test.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#354 docs: fix link and typos on reconciler options readme
  reconciler-options.md
Labels: ok-to-test, size/XS, lgtm, cncf-cla: yes, approved
