Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2023-01, with the labels that each got.

#289 tests: run with a known version of kubectl
  bin/.gitignore
  dev/update-golden
  hack/ci/test.sh
  pkg/patterns/declarative/pkg/applier/exec_test.go
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected-apiserver.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#292 tests: embed interfaces in mocks
  pkg/test/golden/validator.go
  pkg/test/mocks/client.go
  pkg/test/mocks/manager.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#291 :sparkles: bump k8s from 1.25 to 1.26
  applylib/go.mod
  applylib/go.sum
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
  go.mod
  go.sum
  mockkubeapiserver/go.mod
  mockkubeapiserver/go.sum
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#283 add option to configure cascading strategy
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/reconciler.go
Labels: ok-to-test, lgtm, cncf-cla: yes, size/M, approved

#286 mockkubeapiserver: populate errChan
  mockkubeapiserver/memorystorage_watch.go
Labels: size/XS, lgtm, cncf-cla: yes, approved

#290 Update README about required go version
  docs/addon/walkthrough/README.md
Labels: size/XS, lgtm, cncf-cla: yes, approved

#284 mockkubeapiserver: support get of cluster-scoped object
  mockkubeapiserver/apiserver.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#296 Cherry pick of #212: Introduce setters for name and namespace
  pkg/patterns/addon/pkg/status/aggregate.go
  pkg/patterns/addon/pkg/status/kstatus.go
  pkg/patterns/addon/pkg/status/version.go
  pkg/patterns/declarative/pkg/applier/direct.go
  pkg/patterns/declarative/pkg/manifest/objects.go
  pkg/patterns/declarative/pkg/manifest/objects_test.go
  pkg/patterns/declarative/reconciler.go
  pkg/patterns/declarative/watch.go
Labels: sig/api-machinery, lgtm, cncf-cla: yes, size/M, approved

#299 Opt-out the kustomize feature via go build tags
  pkg/patterns/declarative/kustomize/disabled.go
  pkg/patterns/declarative/kustomize/enabled.go
  pkg/patterns/declarative/reconciler.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#301 Add doc for without-kustomize tag
  reconciler-options.md
Labels: lgtm, cncf-cla: yes, size/S, approved
