Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2023-10, with the labels that each got.

#353 Play nicely with third-party testing libraries
  pkg/test/golden/validator.go
Labels: ok-to-test, lgtm, cncf-cla: yes, size/S, approved

#355 mockkubeapiserver: Refactor storage to be pluggable
  mockkubeapiserver/apiserver.go
  mockkubeapiserver/controllers.go
  mockkubeapiserver/deleteresource.go
  mockkubeapiserver/getresource.go
  mockkubeapiserver/hooks/crd.go
  mockkubeapiserver/hooks/deployment.go
  mockkubeapiserver/hooks/namespace.go
  mockkubeapiserver/listresource.go
  mockkubeapiserver/memorystorage_watch.go
  mockkubeapiserver/patchresource.go
  mockkubeapiserver/postresource.go
  mockkubeapiserver/putresource.go
  mockkubeapiserver/schemas/Makefile
  mockkubeapiserver/schemas/kubernetes_builtin_schema.go
  mockkubeapiserver/schemas/kubernetes_builtin_schema.meta.yaml
  mockkubeapiserver/schemas/kubernetes_builtin_schema.yaml
  mockkubeapiserver/storage/clock.go
  mockkubeapiserver/storage/hook.go
  mockkubeapiserver/storage/interface.go
  mockkubeapiserver/storage/memorystorage/crd.go
  mockkubeapiserver/storage/memorystorage/memorystorage.go
  mockkubeapiserver/storage/memorystorage/memorystorage_watch.go
  mockkubeapiserver/storage/memorystorage/resourceinfo.go
  mockkubeapiserver/storage/memorystorage/schema.go
  mockkubeapiserver/storage/memorystorage/schema_test.go
  mockkubeapiserver/storage/resourceinfo.go
  mockkubeapiserver/storage/uid.go
  mockkubeapiserver/storage/watchevent.go
  mockkubeapiserver/tools/generate-typeinfo/main.go
  pkg/test/httprecorder/request_log.go
  pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#358 chore: allow tools to be installed with newer versions of go
  examples/guestbook-operator/Makefile
Labels: needs-ok-to-test, lgtm, cncf-cla: yes, size/M, approved

#359 mockkubeapiserver: ensure CRDs become ready
  mockkubeapiserver/apiserver.go
  mockkubeapiserver/hooks/crd.go
  mockkubeapiserver/storage/memorystorage/crd.go
Labels: lgtm, cncf-cla: yes, size/M, approved
