Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2023-04, with the labels that each got.

#325 Prune logic for ApplySetApplier
  applylib/applyset/applyset.go
  applylib/applyset/applyset_test.go
  applylib/applyset/parentref.go
  applylib/applyset/results.go
  applylib/applyset/testdata/testapplyset/expected.yaml
  applylib/go.mod
  applylib/go.sum
  applylib/third_party/forked/github.com/kubernetes/kubectl/pkg/cmd/apply/applyset.go
  applylib/third_party/forked/github.com/kubernetes/kubectl/pkg/cmd/apply/applyset_pruner.go
  applylib/third_party/forked/github.com/kubernetes/kubectl/pkg/cmd/apply/prune.go
  go.mod
  go.sum
  pkg/patterns/declarative/metrics_test.go
  pkg/patterns/declarative/pkg/applier/applylib.go
  pkg/patterns/declarative/pkg/applier/applylib_test.go
  pkg/patterns/declarative/pkg/applier/testdata/applylib/simple1/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/applylib/simple2/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/applylib/simple3/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected.yaml
  pkg/patterns/declarative/pkg/applier/type.go
  pkg/patterns/declarative/reconciler.go
  pkg/restmapper/caching.go
  pkg/restmapper/controllerrestmapper.go
  pkg/test/testreconciler/simpletest/controller_test.go
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#328 restmapper: Ensure that we only access cached fields from a single method
  pkg/restmapper/caching.go
  pkg/restmapper/controllerrestmapper.go
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L

#326 Remove named return values in reconciler
  pkg/patterns/declarative/reconciler.go
  pkg/patterns/declarative/statusinfo.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#309 Leverage kstatus for applyset healthcheck
  applylib/applyset/health.go
  applylib/go.mod
  applylib/go.sum
Labels: lgtm, cncf-cla: yes, approved, size/L

#329 fix: catch unknown kstatus value
  applylib/applyset/health.go
Labels: size/XS, lgtm, cncf-cla: yes, approved

#330 fix: bump applylib in go mod
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, approved, size/L
