Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2023-03, with the labels that each got.

#311 mockkubeapiserver: Always send content-length
  mockkubeapiserver/request.go
Labels: size/XS, lgtm, cncf-cla: yes, approved

#313 Normalize more discovery requests
  pkg/test/httprecorder/request_log.go
  pkg/test/testreconciler/simpletest/controller_test.go
Labels: size/XS, lgtm, cncf-cla: yes, approved

#312 Sort APIResources into a consistent order
  mockkubeapiserver/apiresourcelist.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#314 mockkubeapiserver: send header of watch eagerly
  mockkubeapiserver/listresource.go
Labels: size/XS, lgtm, cncf-cla: yes, approved

#277 Add support for hooks to the reconciler
  applylib/go.mod
  applylib/go.sum
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
  go.mod
  go.sum
  mockkubeapiserver/go.mod
  mockkubeapiserver/go.sum
  pkg/patterns/declarative/hooks.go
  pkg/patterns/declarative/options.go
  pkg/patterns/declarative/pkg/applier/testdata/applylib/simple1/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/applylib/simple2/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/applylib/simple3/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/direct/simple1/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/direct/simple2/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/direct/simple3/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/watch/dynamic.go
  pkg/patterns/declarative/reconciler.go
  pkg/patterns/declarative/watch.go
  pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#272 Better status functions
  pkg/patterns/addon/pkg/status/aggregate.go
  pkg/patterns/addon/pkg/status/basic.go
  pkg/patterns/addon/pkg/status/kstatus.go
  pkg/patterns/declarative/pkg/manifest/objects.go
  pkg/patterns/declarative/reconciler.go
  pkg/patterns/declarative/status.go
  pkg/patterns/declarative/statusinfo.go
  pkg/test/testreconciler/simpletest/controller.go
  pkg/test/testreconciler/simpletest/controller_test.go
  pkg/test/testreconciler/simpletest/testdata/channels/packages/simpletest/0.1.0/manifest.yaml
  pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, size/XL, approved

#308 Better `status.conditions`
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
  go.mod
  go.sum
  pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
  pkg/patterns/addon/pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/patterns/addon/pkg/status/conditions.go
  pkg/patterns/addon/pkg/status/kstatus.go
  pkg/test/httprecorder/request_log.go
  pkg/test/testreconciler/simpletest/controller_test.go
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L

#317 Replace k8s.gcr.io with registry.k8s.io
  examples/guestbook-operator/channels/packages/guestbook/0.1.0/manifest.yaml
  examples/guestbook-operator/controllers/tests/patches-stable.out.yaml
  examples/guestbook-operator/controllers/tests/simple-stable.out.yaml
Labels: size/XS, lgtm, cncf-cla: yes, kind/cleanup, approved

#318 reset status.healthy in each reconcile
  pkg/patterns/addon/pkg/status/kstatus.go
Labels: size/XS, lgtm, cncf-cla: yes, tide/merge-method-squash, approved

#322 testreconciler: pause after reconciliation
  pkg/patterns/declarative/hooks.go
  pkg/patterns/declarative/reconciler.go
  pkg/test/testreconciler/simpletest/controller.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#319 make status.condition patchable
  pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
  pkg/patterns/addon/pkg/apis/v1alpha1/conditions.go
  pkg/patterns/addon/pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/patterns/addon/pkg/status/accessors.go
  pkg/patterns/addon/pkg/status/conditions.go
  pkg/patterns/addon/pkg/status/kstatus.go
  pkg/test/testreconciler/simpletest/controller_test.go
  pkg/test/testreconciler/simpletest/v1alpha1/types.go
  pkg/test/testreconciler/simpletest/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, cncf-cla: yes, tide/merge-method-squash, approved, size/L

#320 mockkubeapiserver: deployments should become healthy
  applylib/go.mod
  applylib/go.sum
  dev/test
  hack/ci/test.sh
  mockkubeapiserver/controllers.go
  pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L

#324 tests: fix race when recording concurrent requests
  pkg/patterns/declarative/pkg/applier/applylib_test.go
  pkg/test/httprecorder/http_recorder.go
  pkg/test/httprecorder/request_log.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#323 controllerrestmapper: implement RESTMappings
  pkg/restmapper/caching.go
  pkg/restmapper/controllerrestmapper.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#316 Simplify List flattening logic
  pkg/patterns/declarative/reconciler.go
Labels: lgtm, cncf-cla: yes, size/S, approved
