Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2023-02, with the labels that each got.

#285 mockkubeapiserver: support PartialObjectMetadata watches
  mockkubeapiserver/listresource.go
  mockkubeapiserver/memorystorage_watch.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#303 mockkubeapiserver: Support direct mode without listening on a socket
  mockkubeapiserver/direct_http.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#302 mockkubeapiserver: Add basic CRD handling
  mockkubeapiserver/apiserver.go
  mockkubeapiserver/controllers.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#294 Replace mock clients with mock kubeapiserver
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
  pkg/test/golden/validator.go
  pkg/test/mocks/cache.go
  pkg/test/mocks/client.go
  pkg/test/mocks/client_test.go
  pkg/test/mocks/manager.go
Labels: lgtm, cncf-cla: yes, approved, size/L

#304 Ignore the .idea folder
  .gitignore
Labels: size/XS, lgtm, cncf-cla: yes, approved

#276 httprecorder: recognize and stream watch responses
  pkg/patterns/declarative/pkg/applier/applylib_test.go
  pkg/test/httprecorder/http_recorder.go
  pkg/test/httprecorder/request_log.go
  pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, approved, size/L
