Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2024-06, with the labels that each got.

#390 Add a kubebuilder marker to patches to preserve unknow fields
  pkg/patterns/addon/pkg/apis/v1alpha1/common_types.go
Labels: ok-to-test, size/XS, lgtm, cncf-cla: yes, approved

#387 owners: promote tomasaschan to owner
  OWNERS
Labels: size/XS, lgtm, cncf-cla: yes, approved

#386 Respect ErrorResults returned from preflight checks
  pkg/patterns/declarative/reconciler.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#388 fix: use correct path to PodSpec for CronJob
  pkg/patterns/declarative/image.go
  pkg/patterns/declarative/image_test.go
  pkg/patterns/declarative/pkg/manifest/objects.go
Labels: ok-to-test, lgtm, cncf-cla: yes, approved, size/L

#384 mockkubeapiserver: set generation on objects
  mockkubeapiserver/hooks/crd.go
  mockkubeapiserver/hooks/deployment.go
  mockkubeapiserver/patchresource.go
  mockkubeapiserver/postresource.go
  mockkubeapiserver/putresource.go
  mockkubeapiserver/storage/memorystorage/memorystorage.go
  mockkubeapiserver/storage/memorystorage/resourceinfo.go
  mockkubeapiserver/storage/resourceinfo.go
  pkg/test/testreconciler/simpletest/testdata/reconcile/direct/create/expected-http.yaml
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#385 mockkubeapiserver: use older kube libraries
  mockkubeapiserver/go.mod
  mockkubeapiserver/go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved

#396 mockkubeapiserver: /apis discovery does not include core group
  applylib/applyset/applyset_test.go
  mockkubeapiserver/apigrouplist.go
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected-apiserver.yaml
  pkg/test/testreconciler/simpletest/testdata/reconcile/ssa/create/expected-http.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#392 Add the ability to set watch timeouts.
  pkg/patterns/declarative/pkg/watch/dynamic.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#393 Expose more health info as well as counts in Apply results
  applylib/applyset/applyset.go
  applylib/applyset/health.go
  applylib/applyset/results.go
Labels: lgtm, cncf-cla: yes, size/M, approved
