Repository kubernetes-sigs/kubebuilder-declarative-pattern, pull requests merged in 2025-04, with the labels that each got.

#419 chore: Add automatic tag and branch creation, triggered by version/TAG_VERSION
  .github/workflows/tag-release.yaml
  dev/bots/projectbots/tag-release
  version/README.md
  version/TAG_VERSION
Labels: lgtm, cncf-cla: yes, size/M, approved

#420 guestbook-operator: update controller-gen
  examples/guestbook-operator/Makefile
  examples/guestbook-operator/api/v1alpha1/zz_generated.deepcopy.go
  examples/guestbook-operator/config/crd/addons.example.org_guestbooks.yaml
  examples/guestbook-operator/config/crd/bases/addons.example.org_guestbooks.yaml
  examples/guestbook-operator/config/crd/bases/addons.example.org_guestbookspecs.yaml
  examples/guestbook-operator/config/rbac/role.yaml
Labels: lgtm, cncf-cla: yes, size/XL, approved

#417 Prepare for v0.20
  applylib/go.mod
  applylib/go.sum
  dev/update-golden
  examples/guestbook-operator/go.mod
  examples/guestbook-operator/go.sum
  go.mod
  go.sum
  go.work
  go.work.sum
  hack/ci/test.sh
  ktest/go.mod
  ktest/go.sum
  mockkubeapiserver/go.mod
  mockkubeapiserver/go.sum
  mockkubeapiserver/tests/testdata/configmap/expected.yaml
  mockkubeapiserver/tests/testdata/secrets_stringdata/expected.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple1/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple2/expected-apiserver.yaml
  pkg/patterns/declarative/pkg/applier/testdata/kubectl/simple3/expected-apiserver.yaml
  version/TAG_VERSION
Labels: lgtm, cncf-cla: yes, size/XXL, approved
